# Generated by Django 3.0.7 on 2020-07-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantpreveducation',
            name='exam_name',
            field=models.CharField(choices=[('1', 'SSC'), ('2', 'HSC')], max_length=10),
        ),
    ]
