# Generated by Django 3.0.8 on 2020-07-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='admit_card',
            field=models.FileField(blank=True, null=True, upload_to='admit_card'),
        ),
    ]
