# Generated by Django 3.0.8 on 2020-07-06 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_admit_card'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Application', 'verbose_name_plural': '1. Applications'},
        ),
    ]
