# Generated by Django 3.0.7 on 2020-07-03 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_institutionsubject'),
        ('applications', '0003_auto_20200702_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_from', models.CharField(max_length=20)),
                ('transaction_number', models.CharField(max_length=50)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.Application')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.InstitutionTransactionMethod')),
            ],
        ),
    ]
