# Generated by Django 3.0.8 on 2020-07-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20200706_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='roll_number',
            field=models.CharField(blank=True, default='4270625075', editable=False, max_length=10, unique=True),
        ),
    ]
