# Generated by Django 3.0.7 on 2020-07-03 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_auto_20200703_1313'),
        ('applications', '0004_applicationpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subject_applications', to='institution.InstitutionSubject'),
            preserve_default=False,
        ),
    ]
