# Generated by Django 3.0.7 on 2020-07-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_application_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='level',
            field=models.CharField(choices=[('1', 'Bachelor'), ('2', 'Masters'), ('3', 'Both')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
