# Generated by Django 3.0.8 on 2020-07-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_auto_20200706_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='roll_number',
            field=models.CharField(default='2375658555', editable=False, max_length=10, unique=True),
        ),
    ]
