# Generated by Django 3.0.7 on 2020-07-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_application_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='level',
            field=models.CharField(choices=[('1', 'Bachelor'), ('2', 'Masters')], max_length=10),
        ),
    ]
