# Generated by Django 3.0.7 on 2020-07-03 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_applicationpayment_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationpayment',
            old_name='intitute',
            new_name='institute',
        ),
    ]
