# Generated by Django 3.0.7 on 2020-07-03 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_auto_20200703_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
