# Generated by Django 3.0.7 on 2020-07-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_applicationpayment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationpayment',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Completed'), ('2', 'Canceled')], default='0', max_length=10),
        ),
    ]
