# Generated by Django 3.0.8 on 2020-07-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_auto_20200708_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='roll_number',
            field=models.CharField(default='8916619331', editable=False, max_length=10, unique=True),
        ),
    ]
