# Generated by Django 3.0.7 on 2020-07-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_applicationpayment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationpayment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
