# Generated by Django 3.0.8 on 2020-07-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_auto_20200708_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='roll_number',
            field=models.CharField(default='6908710534', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Completed'), ('2', 'Canceled'), ('3', 'Waiting')], default='3', max_length=10),
        ),
    ]
