# Generated by Django 3.0.7 on 2020-07-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_applicationpayment_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationpayment',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicationpayment',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
