# Generated by Django 3.0.8 on 2020-07-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_auto_20200709_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='roll_number',
            field=models.CharField(default='3064986355', editable=False, max_length=10, unique=True),
        ),
    ]
