# Generated by Django 3.0.8 on 2020-07-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_auto_20200713_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='roll_number',
            field=models.CharField(default='1568914092', editable=False, max_length=10, unique=True),
        ),
    ]
