# Generated by Django 3.0.8 on 2020-07-06 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationpayment',
            options={'verbose_name': 'ApplicationPayment', 'verbose_name_plural': '2. ApplicationPayment'},
        ),
        migrations.AlterModelOptions(
            name='institutiontransactionmethod',
            options={'verbose_name': 'Institution Transaction', 'verbose_name_plural': '1. Institution Transaction'},
        ),
    ]
