# Generated by Django 3.0.8 on 2020-07-08 17:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20200708_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutiontransactionmethod',
            name='instruction',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
