# Generated by Django 3.0.8 on 2020-07-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20200708_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutiontransactionmethod',
            name='instruction',
            field=models.TextField(),
        ),
    ]
