# Generated by Django 3.0.8 on 2020-07-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_auto_20200708_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationpayment',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
