# Generated by Django 3.0.7 on 2020-06-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('0', 'Admission Holder'), ('1', 'University Holder')], default='0', max_length=10),
        ),
    ]
