# Generated by Django 3.0.7 on 2020-07-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200630_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('0', 'Admission Holder'), ('1', 'Institute Holder')], max_length=10),
        ),
    ]
