# Generated by Django 3.0.7 on 2020-06-30 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationInstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Application Instruction',
                'verbose_name_plural': '1.Application Instruction',
            },
        ),
        migrations.CreateModel(
            name='ApplicationInstructionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='settings.ApplicationInstruction')),
            ],
            options={
                'verbose_name': 'Instruction',
                'verbose_name_plural': '2. Instruction',
            },
        ),
    ]
