# Generated by Django 3.0.8 on 2020-07-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteFaq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': '4.FAQ',
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('site_phone', models.CharField(max_length=20)),
                ('site_email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'SiteInfo',
                'verbose_name_plural': '1.SiteInfo',
            },
        ),
        migrations.AlterModelOptions(
            name='applicationinstruction',
            options={'verbose_name': 'Application Instruction', 'verbose_name_plural': '2.Application Instruction'},
        ),
        migrations.AlterModelOptions(
            name='applicationinstructionlist',
            options={'verbose_name': 'Instruction', 'verbose_name_plural': '3. Instruction'},
        ),
    ]
