# Generated by Django 3.0.7 on 2020-07-01 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutionprofile',
            options={'verbose_name': 'InstitutionProfile', 'verbose_name_plural': '1. InstitutionProfile'},
        ),
        migrations.CreateModel(
            name='AdmissionSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('status', models.BooleanField()),
                ('institute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institute_session', to='institution.InstitutionProfile')),
            ],
        ),
    ]
