# Generated by Django 3.0.7 on 2020-07-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionprofile',
            name='application_fee',
            field=models.FloatField(default=500),
            preserve_default=False,
        ),
    ]
