# Generated by Django 3.0.7 on 2020-07-03 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_institutionprofile_application_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=250)),
                ('level', models.CharField(choices=[('1', 'Bachelor'), ('2', 'Masters')], default='3', max_length=10)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute_subjects', to='institution.InstitutionProfile')),
            ],
        ),
    ]
