# Generated by Django 3.0.8 on 2020-07-06 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_institutionprofile_institute_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteInstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute_instructions', to='institution.InstitutionProfile')),
            ],
            options={
                'verbose_name': 'InstituteInstruction',
                'verbose_name_plural': '3. InstituteInstruction',
            },
        ),
    ]
