# Generated by Django 3.0.8 on 2020-07-06 09:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_instituteinstruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituteinstruction',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
