# Generated by Django 3.0.7 on 2020-07-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_institutionsubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionsubject',
            name='level',
            field=models.CharField(choices=[('1', 'Bachelor'), ('2', 'Masters'), ('3', 'Both')], max_length=10),
        ),
    ]
