# Generated by Django 3.0.8 on 2020-07-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_auto_20200706_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionsession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
