# Generated by Django 3.0.7 on 2020-07-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_remove_institutiontransactionmethod_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionprofile',
            name='gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Both')], default='3', max_length=10),
        ),
    ]
