# Generated by Django 3.0.7 on 2020-07-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_auto_20200703_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionsubject',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
