# Generated by Django 3.0.7 on 2020-07-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0005_institutionsubject_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionsession',
            name='level',
            field=models.CharField(choices=[('1', 'Bachelor'), ('2', 'Masters'), ('3', 'Bachelor & Masters')], default='3', max_length=50),
        ),
    ]
