# Generated by Django 3.0.8 on 2020-07-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0007_auto_20200709_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionprofile',
            name='application_fee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='institutionprofile',
            name='institute_city',
            field=models.CharField(default='Institute City', max_length=150),
        ),
        migrations.AlterField(
            model_name='institutionprofile',
            name='institute_code',
            field=models.CharField(default='Institute Code', max_length=50),
        ),
        migrations.AlterField(
            model_name='institutionprofile',
            name='institute_location',
            field=models.CharField(default='Institute Location', max_length=255),
        ),
        migrations.AlterField(
            model_name='institutionprofile',
            name='institute_name',
            field=models.CharField(default='Institute Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='institutionprofile',
            name='institute_pic',
            field=models.ImageField(blank=True, null=True, upload_to='institution'),
        ),
    ]
