# Generated by Django 3.0.8 on 2020-07-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantpreveducation',
            name='board_name',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi'), ('Rajshahi', 'Rajshahi'), ('Jessore', 'Jessore'), ('Comilla', 'Comilla')], max_length=10),
        ),
        migrations.AlterField(
            model_name='applicantpreveducation',
            name='exam_name',
            field=models.CharField(choices=[('SSC', 'SSC'), ('HSC', 'HSC')], max_length=10),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='freedom_fighter_quota',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='0', max_length=150),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='is_autism',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='0', max_length=150),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='religion',
            field=models.CharField(choices=[('Islam', 'Islam'), ('Hinduism', 'Hinduism'), ('Cristian', 'Cristian'), ('Buddhist', 'Buddhist')], max_length=10),
        ),
    ]
